---

scrape_configs:
  - job_name: windows 
    static_configs:
    - targets: ['192.168.0.21:9182','192.168.0.217:9182','192.168.0.10:9182','192.168.0.16:9182']
rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"


